### ISSUE TITLE
Add ".c-alert__text" class for text color adjustment

### ISSUE THREAD

**Issue by ItsJonQ** [helpscout/seed-alert#3]
Continuing convo from https://github.com/helpscout/seed-alert/pull/2

@nfrancis! Wanted to get your thoughts! Since `.c-alert__text` will be introduced, should `.c-alert` still adjust `h1-h6` automatically by default? Or color adjustment is dependent on `.c-alert__text`.

In our previous convo, I think I landed on only having `.c-alert__text`, but okay with having both! I've become more open to `h1-h6` tweaks testing it out.

Thanks!!

**Comment by nfrancis** [comment]
> should .c-alert still adjust h1-h6 automatically by default?

Your call, but this seems just a little too specific, whereas the `.c-alert__text` class can cover headings and more.

**Comment by ItsJonQ** [comment]
True! I also thought of a use-case were automatic `h1-h6` colouring might not be desired. I've had to build something like this before:

``` html
<div class="c-alert">
  <div class="c-card">
    <h1>Title</h1>
    <p>...</p>
  </div>
</div>
```

For the above example, there's another UI component living inside alert. In this case, you wouldn't want alert to automatically change heading colours for you.

Having `.c-alert__text` means that undesired/unexpected colouring doesn't happen 😍

**Comment by ItsJonQ** [comment]
Addressed in https://github.com/helpscout/seed-alert/pull/4
